sudo: false
language: node_js
node_js:
- "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
script:
  - yarn lint
  - yarn test
  - yarn build
after_success:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
